### ISSUE TITLE
Undistortion and rectification flips image upside-down for ibis

### ISSUE THREAD

**Issue by helenol** [ethz-asl/image_undistort#7]
@ZacharyTaylor We should take a look at this once you're back.

**Comment by ZacharyTaylor** [comment]
The issue here is that ibis and elester place cam0 on different sides of cam1. I will have to go through the frames and find out which one is actually correct and how they ended up different. If elesters is wrong then so is how I calculate the frames as I used the elester config when setting these up..

The stereo rectifier rotates the images by 180 degrees on purpose so that the 2nd camera is always on the same side of the 1st camera.

**Comment by helenol** [comment]
Yep, fixed this problem now by swapping left and right cam. :) Only took me like, 6 hours to figure it out...
Had some other issues we should look at as well but can just talk about it once you're back.
